// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yezkycmlvvmildnwrzrp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inllemt5Y21sdnZtaWxkbndyenJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NjcyNjYsImV4cCI6MjA2ODM0MzI2Nn0.VJoYwQNBR9TO1s_pqyafBxLCEe7jwhY5xHgS_nbEUU4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});